anti_shake_ang_vel:
  _target_: isaaclab.managers.RewardTermCfg
  func: gear_sonic.envs.manager_env.mdp:anti_shake_ang_vel_l2
  weight: -5e-3
  params:
    command_name: "motion"
    threshold: 1.5
    body_names: ["left_wrist_yaw_link", "right_wrist_yaw_link", "head_link"]
