undesired_contacts:
  _target_: isaaclab.managers.RewardTermCfg
  func: gear_sonic.envs.manager_env.mdp:undesired_contacts
  weight: -0.1
  params:
    sensor_cfg:
      _target_: isaaclab.managers.SceneEntityCfg
      name: "contact_forces"
      body_names:
        - "^(?!left_ankle_roll_link$)(?!right_ankle_roll_link$)(?!left_wrist_yaw_link$)(?!right_wrist_yaw_link$)(?!left_elbow_link$)(?!right_elbow_link$).+$"
    threshold: 1.0
