anchor_ori_full:
  _target_: isaaclab.managers.TerminationTermCfg
  func: gear_sonic.envs.manager_env.mdp:exceeded_anchor_ori
  params:
    asset_cfg:
      _target_: isaaclab.managers.SceneEntityCfg
      name: "robot"
    command_name: "motion"
    threshold: 1
