anchor_pos:
  _target_: isaaclab.managers.TerminationTermCfg
  func: gear_sonic.envs.manager_env.mdp:exceeded_anchor_height
  params:
    command_name: "motion"
    threshold: 0.5
    threshold_adaptive: True
    down_threshold: 0.75
    root_height_threshold: 0.5
