ee_body_pos:
  _target_: isaaclab.managers.TerminationTermCfg
  func: gear_sonic.envs.manager_env.mdp:exceeded_body_height
  params:
    command_name: "motion"
    threshold: 0.25
    body_names:
      - "left_ankle_roll_link"
      - "right_ankle_roll_link"
      - "left_wrist_yaw_link"
      - "right_wrist_yaw_link"
