foot_pos_xyz:
  _target_: isaaclab.managers.TerminationTermCfg
  func: gear_sonic.envs.manager_env.mdp:exceeded_body_pos
  params:
    command_name: "motion"
    threshold: 0.5
    body_names:
      - "left_ankle_roll_link"
      - "right_ankle_roll_link"
