# @package algo.config.actor.backbone

defaults:
  - terms/g1_recon@aux_loss_func
  - terms/g1_smpl_latent@aux_loss_func
  - terms/g1_teleop_latent@aux_loss_func
  - terms/teleop_smpl_latent@aux_loss_func
  - terms/reencoded_smpl_g1_latent@aux_loss_func
  - terms/g1_soma_latent@aux_loss_func

aux_loss_coef:
  g1_recon: 0.01
  g1_smpl_latent: 1.0
  g1_teleop_latent: 1.0
  teleop_smpl_latent: 1.0
  reencoded_smpl_g1_latent: 1.0
  g1_soma_latent: 1.0
