# Standard termination composition

defaults:
  - terms/anchor_pos_adaptive@_here_
  - terms/anchor_ori_full@_here_
  - terms/ee_body_pos_adaptive@_here_
  - terms/motion_time_out@_here_
  - terms/foot_pos_xyz@_here_

_target_: gear_sonic.envs.manager_env.mdp.terminations.TerminationsCfg

foot_pos_xyz:
  params:
    threshold: 0.2

anchor_pos:
  params:
    threshold: 0.15

ee_body_pos:
  params:
    threshold: 0.15

anchor_ori_full:
  params:
    threshold: 0.2
