# Standard policy observations composition

defaults:
  - ../terms/gravity_dir@_here_
  - ../terms/base_ang_vel@_here_
  - ../terms/joint_pos@_here_
  - ../terms/joint_vel@_here_
  - ../terms/actions@_here_

_target_: gear_sonic.envs.manager_env.mdp.observations.PolicyCfg
enable_corruption: True
concatenate_terms: True


# define noise for certain terms
gravity_dir:
  history_length: ${actor_prop_history_length}
  noise:
    _target_: isaaclab.utils.noise.AdditiveUniformNoiseCfg
    n_min: -0.05
    n_max: 0.05

base_ang_vel:
  history_length: ${actor_prop_history_length}
  noise:
    _target_: isaaclab.utils.noise.AdditiveUniformNoiseCfg
    n_min: -0.2
    n_max: 0.2

joint_pos:
  history_length: ${actor_prop_history_length}
  noise:
    _target_: isaaclab.utils.noise.AdditiveUniformNoiseCfg
    n_min: -0.01
    n_max: 0.01

joint_vel:
  history_length: ${actor_prop_history_length}
  noise:
    _target_: isaaclab.utils.noise.AdditiveUniformNoiseCfg
    n_min: -0.5
    n_max: 0.5

actions:
  history_length: ${actor_actions_history_length}
