"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DX IDL version: v0.11.0
  Module: unitree_hg.msg.dds_
  IDL file: OdoState_.idl


"""

from enum import auto
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class OdoState_(idl.IdlStruct, typename="unitree_hg.msg.dds_.OdoState_"):
    version: types.array[types.uint32, 2]
    tick: types.uint32
    position: types.array[types.float32, 3]
    orientation: types.array[types.float32, 4]  # quaternion [x, y, z, w]
    linear_velocity: types.array[types.float32, 3]
    angular_velocity: types.array[types.float32, 3]
    crc: types.uint32

